"""Initial migration

Revision ID: 26037a0e175b
Revises: 
Create Date: 2024-11-26 16:14:28.632220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26037a0e175b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_available', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_model', schema=None) as batch_op:
        batch_op.drop_column('is_available')

    # ### end Alembic commands ###
