"""changing BookModel

Revision ID: 5f35aaf2b7c2
Revises: 26037a0e175b
Create Date: 2024-11-26 16:23:39.824682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f35aaf2b7c2'
down_revision = '26037a0e175b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('return_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_model', schema=None) as batch_op:
        batch_op.drop_column('return_date')

    # ### end Alembic commands ###
